### ISSUE TITLE
Symbol not found: _$SBOWV

### ISSUE THREAD

**Issue by lewisgodowski** [LucianoPAlmeida/variable-injector#1]
Trying to get this working as a Run Script in Xcode 10.2 (10E125) with Swift 5, targeting iOS 12.2, on macOS 10.14.4, but running into this error when building:

```
dyld: Symbol not found: _$SBOWV
  Referenced from: /usr/local/lib/libSwiftSyntax.dylib
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /usr/local/lib/libSwiftSyntax.dylib
/Users/XXXXX/Library/Developer/Xcode/DerivedData/template-frkhjdbleikwiuaicceeskqdaisf/Build/Intermediates.noindex/template.build/development-iphonesimulator/template.build/Script-8A70A3CF226F81B900138107.sh: line 7: 49050 Abort trap: 6           variable-injector --file ${SRCROOT}/template/Common/Secrets/CI.swift -- verbose
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by LucianoPAlmeida** [comment]
Hey @lewisgodowski 
Thank's to report this, taking a look at it 👍 
Will come with a feedback as soon as possible :)

**Comment by LucianoPAlmeida** [comment]
Can you try the new [0.2.1](https://github.com/LucianoPAlmeida/variable-injector/releases/0.2.1) with the new installation guide on readme?

**Comment by lewisgodowski** [comment]
Looks good! Thank you! 👍

**Comment by anatoliy-vasylyk-eleks** [comment]
@LucianoPAlmeida Hello! 
I have the same issue with Bitrise.io
![image](https://user-images.githubusercontent.com/43136992/65334787-cdda7180-dbcb-11e9-8c2a-74bcf68212d9.png)

Added as variable-injector as step

![image](https://user-images.githubusercontent.com/43136992/65334836-e9de1300-dbcb-11e9-8002-afda244a4744.png)

Am I doing everything right?

Logs:

dyld: Symbol not found: _$s11SubSequenceSlTl
  Referenced from: /usr/local/bin/variable-injector (which was built for Mac OS X 10.14)
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /usr/local/bin/variable-injector
/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise735726090/step_src/step.sh: line 24:  1527 Abort trap: 6           variable-injector --file ${files} $VERBOSE --ignore ${vars_to_ignore}


Could you help me, please, to figure out what am I doing wrong?

**Comment by LucianoPAlmeida** [comment]
Hey @anatoliy-vasylyk-eleks :) 
Could please shared the stack you are using?
