### ISSUE TITLE
Injector don´t work in Xcode 11.3

### ISSUE THREAD

**Issue by jpipearagon** [LucianoPAlmeida/variable-injector#12]
i run the script in terminal 

`variable-injector --file ${SRCROOT}TestInjector/SwiftInjector/CI.swift --verbose`

but it only prints

`======================================================================

FILE: CI.swift
======================================================================

======================================================================

//
//  CI.swift
//  TestInjector
//
//  Created by Felipe Aragon on 22/04/20.
//  Copyright © 2020 Felipe Aragon. All rights reserved.
//

import Foundation

struct CI {
  static var rappiPayCountry: String = "$(COUNTRY)"
}
`
and the set of the variable is not done

<img width="899" alt="Screen Shot 2020-04-22 at 7 00 06 PM" src="https://user-images.githubusercontent.com/2001714/80044892-87375780-84cb-11ea-926b-030965c5f949.png">

I don't know what happens....

**Comment by LucianoPAlmeida** [comment]
Hey @jpipearagon :)

Humm, the variable to be replaced has to be set on your system via terminal or .bash_profile initialization(and optionally if you want are GUI or CLI processes to see those variables, make sure to set those variables on `lauchctl` and then restart Xcode process).

Those Xcode Environment Variable parameters you have set are passed to the Process (App) at launch time and not at compile time. Meaning that you launch the process with those arguments, that you are only going to have those values if you run the project with Xcode.

With that said to be able to run the variable injector on the terminal and see the replacement, you would have to set those variables in your system, not on Xcode.

**Comment by jpipearagon** [comment]
Ok thanks! I already worked on the terminal. 

But in Xcode it doesn't work for me, Add Run script before compiling:

<img width="1380" alt="Screen Shot 2020-04-23 at 12 10 12 PM" src="https://user-images.githubusercontent.com/2001714/80128533-6cacbf00-855b-11ea-8ae9-ff21923b76fc.png">

and also add environment variable:

<img width="895" alt="Screen Shot 2020-04-23 at 12 11 41 PM" src="https://user-images.githubusercontent.com/2001714/80128694-a4b40200-855b-11ea-858a-947258a7d8a9.png">

my code looks like this:

`struct CI {
  static var country: String = "$(RPPAY_COUNTRY)"
}
`

when I run from xcode it works, but when I run the compile it looks like this:

![Simulator Screen Shot - iPhone 8 - 2020-04-23 at 12 15 16](https://user-images.githubusercontent.com/2001714/80129263-6e2ab700-855c-11ea-94f5-94ba02050ddb.png)

I need to add the variable somewhere to make it work in Xcode?

**Comment by LucianoPAlmeida** [comment]
Ahh, Xcode is what we call  GUI process so to have environment variables available to the Xcode process, you have to make sure to set those variables on `lauchctl` and then restart Xcode process. You can see more details on this [SO thread](https://stackoverflow.com/questions/603785/environment-variables-in-mac-os-x/4567308#4567308). I should probably highlight this on the article :)

**Comment by jpipearagon** [comment]
Yes, you are a "crack" :) I already worked with your reference. Yes, it would be good if you added the reference to the article.

Lastly I want to ask you the last question in bitrise it would only work by adding the environment variables or the variables have to be secret variables:

<img width="272" alt="Screen Shot 2020-04-23 at 3 20 50 PM" src="https://user-images.githubusercontent.com/2001714/80145597-0b461980-8576-11ea-9671-2e04f132b0d9.png">

something like that in `bitrise.yml`:

`envs:
    - COUNTRY: PE`

**Comment by LucianoPAlmeida** [comment]
> Lastly I want to ask you the last question in bitrise it would only work by adding the environment > variables or the variables have to be secret variables:
>

I think it doesn't make any difference, in this case, both secrets and env var are set as an environment variable when the build launches, the only difference is access level, secrets are encrypted and more constrained(they are only visible at the time of builds).

**Comment by jpipearagon** [comment]
thanks, I already made the changes, but it doesn't work in bitrise:

add the variable:

<img width="1676" alt="Screen Shot 2020-04-23 at 9 39 52 PM" src="https://user-images.githubusercontent.com/2001714/80169608-8c6bd380-85ab-11ea-9d79-bb44d6a9d27d.png">

but the script log:

<img width="708" alt="Screen Shot 2020-04-23 at 9 40 42 PM" src="https://user-images.githubusercontent.com/2001714/80169836-1f0c7280-85ac-11ea-937f-3639c740f32d.png">

any ideas, can i check something?

**Comment by LucianoPAlmeida** [comment]
Are you using the lastest version? For XCode 11.3 try to downgrade to the version before that... that’s the only thing I can think now

**Comment by jpipearagon** [comment]
Awesome thanks, i just had to downgrade the version.
