### ISSUE TITLE
dyld: Library not loaded: @rpath/lib_InternalSwiftSyntaxParser.dylib

### ISSUE THREAD

**Issue by hhs1120** [LucianoPAlmeida/variable-injector#16]
When this step run in Bitrise, error occurs. 

used version: 0.3.2

Bitrise Stack used:
Xcode 11.6.x, on macOS 10.15.4 (Catalina)

> dyld: Library not loaded: @rpath/lib_InternalSwiftSyntaxParser.dylib
>   Referenced from: /usr/local/bin/variable-injector
>   Reason: image not found

![스크린샷 2020-07-06 오후 2 27 28](https://user-images.githubusercontent.com/16822168/86558662-f41fa100-bf94-11ea-9576-a660ad516727.png)

**Comment by LucianoPAlmeida** [comment]
@hhs1120 Thank you for reporting this I'll take a look asap :)

**Comment by LucianoPAlmeida** [comment]
Should be fixed by https://github.com/LucianoPAlmeida/variable-injector/releases/tag/0.3.3 too
