### ISSUE TITLE
Doesn't execute properly in Xcode 12.0.x - Requires SwiftSyntax version to be updated. 

### ISSUE THREAD

**Issue by jaswanthm** [LucianoPAlmeida/variable-injector#17]
Hi, 

I tried using this step in the Xcode 12.0.x, Mac OS 10.15.5.

It throws this error : `Error: SwiftSyntax parser library isn't compatible`

Possible fix is to update the SwiftSyntax to package to the latest version. "swift-5.3-RELEASE" ?

Current Package.swift
`.package(name: "SwiftSyntax", url: "https://github.com/apple/swift-syntax.git", .exact("0.50200.0")),`

I got it to work with the following
`.package(name: "SwiftSyntax", url: "https://github.com/apple/swift-syntax", .revision("swift-5.3-RELEASE")),`

Please let me know if you need more info. Ta

**Comment by LucianoPAlmeida** [comment]
Thanks for reporting @jaswanthm :) 
This should be fixed in [0.3.3](https://github.com/LucianoPAlmeida/variable-injector/releases/tag/0.3.3) so closing this. Feel free to re-open if you see it has some issue

**Comment by jaswanthm** [comment]
Awesome. Thanks for getting back so quickly.
