### ISSUE TITLE
How as do for not upload the file changed to Repository?

### ISSUE THREAD

**Issue by xmoba-pablo** [LucianoPAlmeida/variable-injector#2]
When I execute the script, the file CI.swift is modified and compiled. 
But, if I do commit and push, I am uploading the CI.swift modified with the secret variables to repository. It is wrong, the file CI.swift must back at status initial without changes.

How can I do commit and push the CI.swift without the secret variables?

**Comment by LucianoPAlmeida** [comment]
Hey, I think the only way is not to add the file when you commit. If you are using Xcode is just uncheck the CI.swift file when commiting. If you are doing on the terminal is just git add all the other files but not this one :))
