### ISSUE TITLE
Build failed randomly in xcode 13.1

### ISSUE THREAD

**Issue by justBA** [LucianoPAlmeida/variable-injector#22]
When i build on xcode 12.4 everything is fine. But when i update to xcode 13 and this error happens.

> remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
error: input file '/Users/justtttBA/Documents/code/DemoProject/ios/ContactPicker/Secrets/EnvironmentSecrets-generated.swift' was modified during the build
error: input file '/Users/justtttBA/Documents/code/DemoProject/ios/ContactPicker/Secrets/EnvironmentSecrets-generated.swift' was modified during the build
Command CompileSwiftSources failed with a nonzero exit code

**Comment by LucianoPAlmeida** [comment]
Can you provide the version you are using? To work with Xcode 13 we have to use the latest #0.3.5 :)

**Comment by justBA** [comment]
I think that my problem when i tried to remove old generated file when it run script manually, force copy solve my problem.
Thanks
