### ISSUE TITLE
Xcode 13.3: The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax

### ISSUE THREAD

**Issue by MarekSlaninka** [LucianoPAlmeida/variable-injector#23]
Hi @LucianoPAlmeida it seems that with Xcode 13.3 this is once again broken. I tried to update SwiftSyntax to 0.50600.1, but then there was an error in code, so build didn't go through

**Comment by LucianoPAlmeida** [comment]
It happens whenever there is a new version of the language/swift-syntax released. I'll update and make a release this weekend =]

**Comment by LucianoPAlmeida** [comment]
Release #0.3.6 is out, just update it and issue should be fixed
