### ISSUE TITLE
Xcode 13.4.1: The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax

### ISSUE THREAD

**Issue by MarekSlaninka** [LucianoPAlmeida/variable-injector#25]
Hi @LucianoPAlmeida it seems that with Xcode 13.4 this is once again broken.

**Comment by LucianoPAlmeida** [comment]
Which version of this are you using? Is 0.3.6? In theory it should only break in 14 ... but I may be wrong =]

**Comment by MarekSlaninka** [comment]
Hi, Im using 13.4.1. I fixed it locally with updating **_swift-argument-parser_** to 1.1.3

**Comment by LucianoPAlmeida** [comment]
> Hi, Im using 13.4.1. I fixed it locally with updating **_swift-argument-parser_** to 1.1.3

I meant version of the variable-injector ...
Not really sure how updating arg parser fixes, but if it does that's good 😊
