### ISSUE TITLE
Bitrise Variable Injector Version 0.1.2 no longer injects variables

### ISSUE THREAD

**Issue by Ghassen-Ferchichi** [LucianoPAlmeida/variable-injector#29]
Greetings,
Since the last fix for Xcode 14 and with the new version 0.1.2, the variable injector no longer injects variables, I also noticed that apparently it can no longer read the file that contains the variables to be injected. 
Here is a preview of the logs before version 0.1.2 and after:
This is before
<img width="1037" alt="Capture d’écran 2022-11-09 à 09 43 15" src="https://user-images.githubusercontent.com/63983483/200787341-28d14023-e0e6-4e60-bc43-2db2a1827275.png">

And this is after
<img width="909" alt="Capture d’écran 2022-11-09 à 09 56 59" src="https://user-images.githubusercontent.com/63983483/200787491-c59a50a3-92f3-4b6b-9539-b1c969dda9a4.png">

PN: I tested this with the version 0.3.7 and with 0.3.6
If you need any more informations, I'll be happy to communicate it to you, thanks in advance

**Comment by LucianoPAlmeida** [comment]
I think we know the issue 🤦‍♂️

**Comment by LucianoPAlmeida** [comment]
Working on 0.1.3

**Comment by LucianoPAlmeida** [comment]
This is being tracked here https://github.com/LucianoPAlmeida/bitrise-step-swift-environment-variable-injector/issues/9 already, closing. Thank you for the detailed info!

**Comment by Ghassen-Ferchichi** [comment]
Thank you for getting back to me, great news, can't wait
