### ISSUE TITLE
`install-binary.sh` in `0.3.0` tag downloads `0.2.1` release

### ISSUE THREAD

**Issue by OliverPearmain-Pusher** [LucianoPAlmeida/variable-injector#8]
Shouldn't the `0.3.0` tag  version of `install-binary.sh` script download the `0.3.0` release?

https://github.com/LucianoPAlmeida/variable-injector/blob/055fd99db1df5b962b57a3484378ad66ed7fa00b/scripts/install-binary.sh#L3

**Comment by LucianoPAlmeida** [comment]
You right, Thank you for catching this!

**Comment by LucianoPAlmeida** [comment]
Adjusted in the new tag :)
https://github.com/LucianoPAlmeida/variable-injector/releases/tag/0.3.1

Thank you

**Comment by OliverPearmain-Pusher** [comment]
Awesome, thanks for fixing.
